#!/usr/bin/perl
use strict;
use warnings;
use Gtk2 '-init';
use YAML;

my $mw = Gtk2::Window->new;

my (@formats) =  Gtk2::Gdk::Pixbuf->get_formats;
print Dump([\@formats]);

$mw->show_all();

$mw->signal_connect('destroy', sub { Gtk2->main_quit });
Gtk2->main;
##############################################################
