#!/usr/bin/perl
use warnings;
use strict;
use Glib qw/TRUE FALSE/;
use Gtk2 '-init';

my $window = Gtk2::Window->new('toplevel');
$window->set_title('Z');
$window ->signal_connect( 'destroy' => \&delete_event );
$window->set_border_width(10);
$window->set_size_request(300,200);

my $red = Gtk2::Gdk::Color->new (0xFFFF,0,0);
my $green = Gtk2::Gdk::Color->new (0,0xFFFF,0);
my $blue = Gtk2::Gdk::Color->new (0,0,0xFFFF);
my $blue1 = Gtk2::Gdk::Color->new (0,0xCCCC,0xFFFF);

my $vbox = Gtk2::VBox->new( FALSE, 6 );
$window->add($vbox);
$vbox->set_border_width(2);

my $hbox= Gtk2::HBox->new( FALSE, 6 );
$vbox->pack_end($hbox,FALSE,FALSE,0);
$hbox->set_border_width(2);

my $frame0 = Gtk2::Frame->new('Controls');
$vbox->pack_end( $frame0, FALSE, FALSE, 0 );
$frame0->set_border_width(3);

my $hbox0 = Gtk2::HBox->new( FALSE, 6 );
$frame0->add($hbox0);
$hbox0->set_border_width(3);

my $button = Gtk2::Button->new_from_stock('gtk-quit');
$hbox0->pack_end( $button, FALSE, FALSE, 0 );
$button->signal_connect( clicked => \&delete_event );

my $colbut1 = Gtk2::ColorButton->new();
$colbut1->set_color($blue1);
$hbox0->pack_end( $colbut1, FALSE, FALSE, 0 );
$colbut1->signal_connect( clicked => sub{ 
            print $colbut1->get_color(),"\n";      
             });

$window->modify_bg ('normal', $green);
$frame0->modify_bg ('normal', $red);


$window->show_all();
Gtk2->main;
#####################################
sub delete_event {
Gtk2->main_quit;
return FALSE;
}
