#!/usr/bin/perl
use strict;
use Glib qw( TRUE FALSE );
use Gtk2 -init;

my $window = new Gtk2::Window("toplevel");
$window->set_border_width(3);
my $toggle = new Gtk2::ToggleButton("block");

$window->add($toggle);

$toggle->signal_connect(
    toggled => sub {
        $_[0]->set_label(
            $_[0]->get_active
            ? "unblock"
            : "block"
        );
    }
);
$window->signal_connect(
    "delete-event" => sub {

        # if we are blocked, do nothing:
        return TRUE if $toggle->get_active;

        # otherwise stop the main loop and let
        # the default handler destroy the window.
        Gtk2->main_quit;
        return FALSE;
    }
);
$window->show_all();
Gtk2->main();

