#!/usr/bin/perl -w
use strict;
use Gtk2;
use Glib qw/TRUE FALSE/;
Gtk2->init;

my $window = Gtk2::Window->new;
$window ->signal_connect( 'destroy' => \&delete_event );
#notice destroy dosn't work with a manual loop

$window->add(Gtk2::Label->new("Hello World"));

my $count = 0;
my $timer = Glib::Timeout->add (1000,\&show_loop);

$window->show_all;

#Gtk2->main;
#do_something_cpu_intensive ($item);

while(1){
Gtk2->main_iteration while Gtk2->events_pending;
}


########################################
sub show_loop{
  $count++;
  print "$count\n";
  return 1;
}
#####################################
sub delete_event {
Gtk2->main_quit;
return FALSE;
}

