#!/usr/bin/perl -w
use strict;
use Glib ':constants';
use Gtk2 -init;
my $window = Gtk2::Window->new;
$window->signal_connect( destroy => sub { Gtk2->main_quit } );
my $h = new_with_range Gtk2::HScale( 0, 10, 1 );
$h->signal_connect(
    value_changed => sub {
        print "value-changed : now " . $h->get_value . "\n";
    }
);
$window->add($h);
$window->set_default_size(200,200);
$window->show_all;
Gtk2->main;
