#!/usr/bin/perl
use warnings;
use strict;
use Gtk2 -init;
use Glib qw(TRUE FALSE);

my $window = Gtk2::Window->new;
$window->signal_connect(delete_event => sub { Gtk2->main_quit; });

my $label = Gtk2::Label->new('' . time());
my $font = Gtk2::Pango::FontDescription->from_string("Sans Bold 48");
$label->modify_font($font);

Glib::Timeout->add(250, sub { $label->set_text('' . time()); TRUE; });

$window->add($label);

$window->show_all;

Gtk2->main;
